---
rules:
  - name: No variables in settings
    targets: /settings
    must: yes
    contain: //variables

  - name: Username in settings having type=Client is not empty
    having: //type[text()="Client"]
    must: no
    contain: //username[text()]

  - name: No nodes with value > 1
    targets: //node
    must: no
    contain: //node[text()>1]

  - name: Empty tag
    targets: //node
    must: no
    contain: //node[not(text())]

  - name: Tag contains bad word
    must: no
    contain: //tag[contains(text(), "bad word")]
